name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Add Secrets Key
      env:
        BASE_URL: ${{secrets.BASE_URL}}
        API_KEY: ${{secrets.API_KEY}}
      run: |
        echo BASE_URL=\"$BASE_URL\" > ./local.properties
        echo API_KEY=\"$API_KEY\" > ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Build Project
      run: ./gradlew assembleDebug
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/
      
